<?php
/**
 * @file
 * Contains BBD paragraphs main functionality.
 */

/**
 * Implements hook_preprocess_paragraph().
 */
function bbd_paragraphs_preprocess_paragraph(&$variables) {
  $paragraph_type = $variables['paragraph']->getParagraphType();

  if (!isset($variables['attributes']['class'])) {
    $variables['attributes']['class'] = [];
  }

  // Customize "Paragraph: Accordion".
  if ($paragraph_type->id == 'accordion') {
    $variables['attributes']['class'][] = 'expandable-content-section';

    $variables['#attached']['library'][] = 'bbd_paragraphs/bbd_paragraphs.accordion';
  }

  // Customize "Paragraph: Banner".
  if ($paragraph_type->id == 'paragraph_banner') {
    $variables['attributes']['class'][] = 'banner-content-section';

    $variables['#attached']['library'][] = 'bbd_paragraphs/bbd_paragraphs.banner';
  }
}

/**
 * Implements hook_theme().
 */
function bbd_paragraphs_theme() {
  return [
    'paragraph__paragraph_banner' => [
      'template' => 'paragraph--paragraph-banner',
      'base hook' => 'paragraph',
    ],
    'modal' => [
      'variables' => [
        'content' => NULL,
        'target_id' => NULL,
        'open_link_text' => NULL,
        'close_link_text' => NULL,
      ],
    ],
  ];
}
